### ISSUE TITLE
Update README quickstart

### ISSUE THREAD

**Issue by brendanhoganvt** [kkoralsky/goldsprints#1]
README quickstart references file `main.py` which no longer exists in repo.  I believe it should reference `gold.py`.

Running file directly implies python installation in `/usr/bin/env`, otherwise a quickstart command `python gold.py --help` may be a safer suggestion for aspiring users.

**Comment by kkoralsky** [comment]
Thank you for your intrest in the project. I have updated REAME little bit. If you have any more concerns feel free to ask. PR are also very welcome.

**Comment by brendanhoganvt** [comment]
Thank you for clarifying the README!  I will send you questions or PRs as I try and test it further.
